Prosegur.LV.SOL.Dashboard.UI.Web/Controllers/DashboardController.cs
using System.Web.Mvc;

namespace Prosegur.LV.SOL.Dashboard.UI.Web.Controllers
{
    [Authorize]
    public class DashboardController : Controller
    {
        public ActionResult Route()
        {
            return View();
        }

        public ActionResult Programmation()
        {
            return View();
        }

        public ActionResult ProgrammationBar()
        {
            return View();
        }

        public ActionResult CierresFacturacionBar()
        {
            return View();
        }
    }
}

Prosegur.LV.SOL.Dashboard.UI.Web/Controllers/IntegrationController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using log4net;
using Prosegur.LV.SOL.Dashboard.Core;
using Prosegur.LV.SOL.Dashboard.Entities;
using Prosegur.LV.SOL.Dashboard.UI.Web.Models;

namespace Prosegur.LV.SOL.Dashboard.UI.Web.Controllers
{
    [SessionState(System.Web.SessionState.SessionStateBehavior.Disabled)]
    [Authorize]
    public class IntegrationController : Controller
    {
        public ActionResult OTIntegrationStatesPartial(Models.OTIntegrationFilterViewModel model)
        {
            ViewData.Add("ChartTitle", "Estado de Integración de OTs");

            if (!Request.IsAjaxRequest())
            {
                IEnumerable<Models.DelegationModel> modeloDelegaciones = new List<Models.DelegationModel>();

                Prosegur.LV.SOL.Dashboard.UI.Web.Models.UserData datosUsuario =
                    (Prosegur.LV.SOL.Dashboard.UI.Web.Models.UserData)HttpContext.User;

                IList<SOLDelegacion> solDelegaciones;
                Usuario coreUsuario = new Usuario();

                solDelegaciones = coreUsuario.GetUsuarioDelegaciones(datosUsuario.UserCode);

                if (solDelegaciones != null)
                {
                    modeloDelegaciones = from d in solDelegaciones
                                         select new DelegationModel()
                                         {
                                             Code = d.Codigo,
                                             Description = d.Descripcion
                                         };
                }

                model.PeriodFromHours = 0;
                model.Delegations = new SelectList(modeloDelegaciones, "Code", "Description");
            }
            else
            {
                if (model.DelegationCodes != null && model.DelegationCodes.Count() > 0)
                {
                    Prosegur.LV.SOL.Dashboard.Core.SOLOrdenDeTrabajo coreOrdenDeTrabajo = new Prosegur.LV.SOL.Dashboard.Core.SOLOrdenDeTrabajo();

                    IntegrationSummaryViewModel mensajesPendientes = new IntegrationSummaryViewModel()
                    {
                        Quantity = 0,
                        IntegrationState = IntegrationStateModel.GetByCode(Configuracion.CodigoEstadoPendiente)
                    };

                    IntegrationSummaryViewModel mensajesErroneos = new IntegrationSummaryViewModel()
                    {
                        Quantity = 0,
                        IntegrationState = IntegrationStateModel.GetByCode(Configuracion.CodigoEstadoError)
                    };

                    List<Models.IntegrationSummaryViewModel> list = new List<Models.IntegrationSummaryViewModel>() { mensajesPendientes, mensajesErroneos };

                    model.OTIntegrationStatesSummary = list;

                    try
                    {
                        IList<JMSEnvioMensaje> entSolJmsEnvioMensajes = coreOrdenDeTrabajo.GetMensajesIntegracion(model.DelegationCodes.ToArray(), model.PeriodFromHours);

                        mensajesPendientes.Quantity = entSolJmsEnvioMensajes.Where(m => m.Estado == Configuracion.CodigoEstadoPendiente).Count();
                        mensajesErroneos.Quantity = entSolJmsEnvioMensajes.Where(m => m.Estado == Configuracion.CodigoEstadoError).Count();
                    }
                    catch (Prosegur.LV.SOL.Dashboard.Core.Excepciones.ExcepcionBase)
                    {
                        throw;
                    }
                    catch (Exception ex)
                    {
                        ILog log = LogManager.GetLogger(typeof(IntegrationController));

                        log.ErrorFormat("Message: {0} \n Stack: {1}", ex.Message, ex.StackTrace);

                        throw new HttpException(ex.Message);
                    }
                }

                string jsonSerializedData = new JavaScriptSerializer().Serialize(model);

                return Json(new { result = true, data = jsonSerializedData });
            }

            ViewData.Add("ViewName", "OTIntegrationStatesPartial");
            ViewData.TemplateInfo.HtmlFieldPrefix = ViewData["ViewName"].ToString();
            return PartialView(model);
        }

        public ActionResult OTErrorQueueMessages(Models.OTIntegrationFilterViewModel model)
        {
            ViewBag.OTDetailsTitle = "Detalles Mensajes OT";

            List<JmsQueueOTMessage> mensajes = new List<JmsQueueOTMessage>();

            try
            {
                Prosegur.LV.SOL.Dashboard.Core.SOLOrdenDeTrabajo coreOrdenDeTrabajo = new Prosegur.LV.SOL.Dashboard.Core.SOLOrdenDeTrabajo();

                IList<JMSEnvioMensaje> entSolJmsEnvioMensajes = coreOrdenDeTrabajo.GetMensajesIntegracionError(model.DelegationCodes.ToArray(), model.PeriodFromHours);

                if (entSolJmsEnvioMensajes != null && entSolJmsEnvioMensajes.Count() > 0)
                {
                    IList<Prosegur.LV.SOL.Dashboard.Entities.SOLOrdenDeTrabajo> entOrdenesDeTrabajo = coreOrdenDeTrabajo.GetListado(entSolJmsEnvioMensajes.Select(m => m.Id).ToArray());

                    if (entOrdenesDeTrabajo != null)
                    {
                        foreach (Prosegur.LV.SOL.Dashboard.Entities.JMSEnvioMensaje entSolJmsEnvioMensaje in entSolJmsEnvioMensajes)
                        {
                            Prosegur.LV.SOL.Dashboard.Entities.SOLOrdenDeTrabajo entOrdenDeTrabajo =
                                entOrdenesDeTrabajo.Where(o => o.OidOt == entSolJmsEnvioMensaje.Id).FirstOrDefault();

                            mensajes.Add(new JmsQueueOTMessage()
                            {
                                CodDelegacion = entSolJmsEnvioMensaje.Delegacion,
                                RouteCode = entOrdenDeTrabajo.CodigoRuta,
                                CodServicio = entOrdenDeTrabajo.CodigoServicio,
                                SequenceCode = entOrdenDeTrabajo.CodigoSecuencia,
                                Date = entOrdenDeTrabajo.FechaProgramadaInicio,
                                Observation = entSolJmsEnvioMensaje.Observacion
                            });
                        }
                    }
                }

                return Json(new { result = true, data = this.RenderPartialView("JmsQueueOTMessages", mensajes) });
            }
            catch (Prosegur.LV.SOL.Dashboard.Core.Excepciones.ExcepcionBase)
            {
                throw;
            }
            catch (Exception ex)
            {
                ILog log = LogManager.GetLogger(typeof(IntegrationController));

                log.ErrorFormat("Message: {0} \n Stack: {1}", ex.Message, ex.StackTrace);

                throw new HttpException(ex.Message);
            }
        }

        public ActionResult ProgrammationServicesStatesPartial(ProgrammationFilterViewModel model)
        {
            ViewData.Add("ChartTitle", "Servicios General");

            if (!Request.IsAjaxRequest())
            {
                IEnumerable<Models.DelegationModel> modeloDelegaciones = new List<Models.DelegationModel>();

                Prosegur.LV.SOL.Dashboard.UI.Web.Models.UserData datosUsuario =
                    (Prosegur.LV.SOL.Dashboard.UI.Web.Models.UserData)HttpContext.User;

                IList<SOLDelegacion> solDelegaciones;
                Usuario coreUsuario = new Usuario();

                solDelegaciones = coreUsuario.GetUsuarioDelegaciones(datosUsuario.UserCode);

                if (solDelegaciones != null)
                {
                    modeloDelegaciones = from d in solDelegaciones
                                         select new DelegationModel()
                                         {
                                             Code = d.Codigo,
                                             Description = d.Descripcion
                                         };
                }

                model.Delegations = new SelectList(modeloDelegaciones, "Code", "Description");
            }
            else
            {
                try
                {
                    if (model.DelegationCodes != null && model.DelegationCodes.Count > 0)
                    {
                        IntegracionSOLSIGII integracionSOLSIGII = new IntegracionSOLSIGII();

                        Tuple<IEnumerable<SOLIntegracionProgramacion>, IEnumerable<JMSEnvioMensaje>, IEnumerable<SIGIIPlanta>> estadoProgramacionDeServicios = integracionSOLSIGII.EstadoProgramacionDeServicios(model.ProgrammationDate, model.DelegationCodes.ToArray());

                        model.ProgrammationStatesSummary = from i in estadoProgramacionDeServicios.Item1
                                                           select new ProgrammationStateSummaryViewModel()
                                                           {
                                                               ProgrammationState = ProgrammationStateModel.ConvertFrom(i.Estado),
                                                               Quantity = i.Cantidad
                                                           };

                        if (estadoProgramacionDeServicios.Item2 != null)
                        {
                            model.ErrorMessagesId = (from m in estadoProgramacionDeServicios.Item2
                                                     select m.JmsId).ToList();
                        }

                        if (estadoProgramacionDeServicios.Item3 != null)
                        {
                            model.SigIIProgrammationPendings = (from s in estadoProgramacionDeServicios.Item3
                                                                select s.Codigo).ToList();
                        }

                    }

Prosegur.LV.SOL.Dashboard.UI.Web/Controllers/RouteController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using log4net;
using Prosegur.LV.SOL.Dashboard.Core;
using Prosegur.LV.SOL.Dashboard.Entities;
using Prosegur.LV.SOL.Dashboard.UI.Web.Models;

namespace Prosegur.LV.SOL.Dashboard.UI.Web.Controllers
{
    [SessionState(System.Web.SessionState.SessionStateBehavior.Disabled)]
    [Authorize]
    public class RouteController : Controller
    {
        public ActionResult RouteBalancesPartial(RouteBalanceFilterViewModel model)
        {
            ViewData.Add("ChartTitle", "Balanceo de Rutas");

            if (!Request.IsAjaxRequest())
            {
                IEnumerable<Models.DelegationModel> modeloDelegaciones = new List<Models.DelegationModel>();

                Prosegur.LV.SOL.Dashboard.UI.Web.Models.UserData datosUsuario =
                    (Prosegur.LV.SOL.Dashboard.UI.Web.Models.UserData)HttpContext.User;

                IList<SOLDelegacion> solDelegaciones;
                Usuario coreUsuario = new Usuario();

                solDelegaciones = coreUsuario.GetUsuarioDelegaciones(datosUsuario.UserCode);

                if (solDelegaciones != null)
                {
                    modeloDelegaciones = from d in solDelegaciones
                                         select new DelegationModel()
                                         {
                                             Code = d.Codigo,
                                             Description = d.Descripcion
                                         };
                }

                model.Delegations = new SelectList(modeloDelegaciones, "Code", "Description");
            }
            else
            {
                try
                {
                    if (model.DelegationCodes != null && model.DelegationCodes.Count() > 0)
                    {
                        IntegracionSOLSIGII integracionSOLSIGII = new IntegracionSOLSIGII();

                        Tuple<IEnumerable<Entities.SOLIntegracionRuta>, IEnumerable<Entities.SOLRuta>> estadoIntegracionRutas = integracionSOLSIGII.EstadoDeRutas(model.RouteDate, model.DelegationCodes.ToArray());

                        model.StateRoutesSummary = from i in estadoIntegracionRutas.Item1
                                                   select new IntegrationStateRouteSummaryViewModel()
                                                   {
                                                       Quantity = i.Cantidad,
                                                       RouteState = IntegrationRouteStateModel.ConvertFrom(i.Estado)
                                                   };

                        if (estadoIntegracionRutas.Item2 != null)
                        {
                            model.RoutesWithError = estadoIntegracionRutas.Item2.Select(r => r.Codigo).ToList();
                        }
                    }

                    var jsonSerializedData = new JavaScriptSerializer().Serialize(model);

                    return Json(new { result = true, data = jsonSerializedData });
                }
                catch (Prosegur.LV.SOL.Dashboard.Core.Excepciones.ExcepcionBase)
                {
                    throw;
                }
                catch (Exception ex)
                {
                    ILog log = LogManager.GetLogger(typeof(RouteController));

                    log.ErrorFormat("Message: {0} \n Stack: {1}", ex.Message, ex.StackTrace);

                    throw new HttpException(ex.Message);
                }
            }

            ViewData.Add("ViewName", "RoutesBalancesPartial");
            ViewData.TemplateInfo.HtmlFieldPrefix = ViewData["ViewName"].ToString();
            return PartialView(model);
        }

        public ActionResult RouteIntegrationDetailsPartial(List<int> routeWithErrors, DateTime fecRuta)
        {
            ViewBag.OTDetailsTitle = "Integracion de OTs/Servicios";

            try
            {
                IntegracionSOLSIGII integracionSOLSIGII = new IntegracionSOLSIGII();

                IList<Tuple<Entities.SOLOrdenDeTrabajo, Entities.SIGIIHojaDeRuta>> detalleDeRutas = integracionSOLSIGII.DetalleDeRutas(routeWithErrors.ToArray(), fecRuta);

                var listadoDetalle = from d in detalleDeRutas
                                     let solOrdenDeTrabajo = d.Item1
                                     let sigIIHojaDeRuta = d.Item2
                                     select new RouteIntegrationDetails()
                                     {
                                         SolRouteCode = (solOrdenDeTrabajo != null ? (int?)solOrdenDeTrabajo.CodigoRuta : null),
                                         SolOTCode = (solOrdenDeTrabajo != null ? solOrdenDeTrabajo.OidOt : null),
                                         SolServiceCode = (solOrdenDeTrabajo != null ? solOrdenDeTrabajo.CodigoServicio : null),
                                         SolSequenceCode = (solOrdenDeTrabajo != null ? (int?)solOrdenDeTrabajo.CodigoSecuencia : null),
                                         SolOTProgrammedBeginDateTime = (solOrdenDeTrabajo != null ? (DateTime?)solOrdenDeTrabajo.FechaProgramadaInicio : null),
                                         SigRouteCode = (sigIIHojaDeRuta != null ? (int?)sigIIHojaDeRuta.Recorrido : null),
                                         SigControlCode = (sigIIHojaDeRuta != null ? (int?)sigIIHojaDeRuta.Control : null),
                                         SigServiceDate = (sigIIHojaDeRuta != null ? sigIIHojaDeRuta.FechaProceso.ToString("yyyy/MM/dd") : null),
                                         SigServiceDateTime = (sigIIHojaDeRuta != null ? (DateTime?)new DateTime(sigIIHojaDeRuta.FechaProceso.Year, sigIIHojaDeRuta.FechaProceso.Month, sigIIHojaDeRuta.FechaProceso.Day, sigIIHojaDeRuta.HoraProceso.Hour, sigIIHojaDeRuta.HoraProceso.Minute, sigIIHojaDeRuta.HoraProceso.Second) : null)
                                     };

                return Json(new { result = true, data = this.RenderPartialView(listadoDetalle) });
            }
            catch (Prosegur.LV.SOL.Dashboard.Core.Excepciones.ExcepcionBase)
            {
                throw;
            }
            catch (Exception ex)
            {
                ILog log = LogManager.GetLogger(typeof(RouteController));

                log.ErrorFormat("Message: {0} \n Stack: {1}", ex.Message, ex.StackTrace);

                throw new HttpException(ex.Message);
            }
        }
	}    
}

Prosegur.LV.SOL.Dashboard.UI.Web/Views/Dashboard/CierresFacturacionBar.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@Scripts.Render("~/bundles/highCharts")



<div class="row my-2">
    <div class="col-sm-2">
        @{ Html.RenderPartial("IntegrationBarStateReferencesPartial", Prosegur.LV.SOL.Dashboard.UI.Web.Models.IntegrationBarStateModel.GetAll()); }
    </div>
    <div class="col-sm-8">
        @{ Html.RenderAction("CierresFactPorDelegacionPartial", "Integration"); }
    </div>
    @*<div class="col-sm-4">
            @{ Html.RenderAction("ProgrammationBarPerRouteResourcesStatesPartial", "Integration"); }
        </div>
        <div class="col-sm-4">
            @{ Html.RenderAction("ProgrammationBarPerGroupStatesPartial", "Integration"); }
        </div>*@
</div>
@*<div class="row my-2">
    <div class="col-sm-4">
        @{ Html.RenderPartial("IntegrationBarStateReferencesPartial", Prosegur.LV.SOL.Dashboard.UI.Web.Models.IntegrationBarStateModel.GetAll()); }
    </div>
    @*<div class="col-sm-4">
        @{ Html.RenderAction("ProgrammationBarServicesStatesPartial", "Integration"); }
    </div>
    <div class="col-sm-4">
        @{ Html.RenderAction("ProgrammationBarResourcesStatesPartial", "Integration"); }
    </div>
</div>*@

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Prosegur.LV.SOL.Dashboard.UI.Web/Views/Dashboard/IntegrationBarStateReferencesPartial.cshtml
@model IEnumerable<Prosegur.LV.SOL.Dashboard.UI.Web.Models.IntegrationBarStateModel>

<style>

    .dot {
        height: 25px;
        width: 25px;
        border-radius: 50%;
        display: inline-block;
    }

</style>

<div class="card" style="width: 18rem;">
    <div class="card-header">
        Referencia
    </div>
    <ul class="list-group list-group-flush">
        @Html.EditorFor(model => Model)
    </ul>
</div>

Prosegur.LV.SOL.Dashboard.UI.Web/Views/Dashboard/Programmation.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@Scripts.Render("~/bundles/highCharts")

<script>

    Highcharts.Chart.prototype.addChartLabel = function (type, message) {

        element = this.renderer.label(message);

        if (type == 'error') {

            element.css({
                color: '#FFFFFF',
                fontSize: '1.1em',
                width: 350
            })
            .attr({
                fill: '#ff0000',
                padding: 8,
                r: 5,
                zIndex: 6
            });

        }

        if (type == 'warning') {

            element.css({
                color: '#000000',
                fontSize: '3em'
            })
            .attr({
                fill: '#ffc107',
                padding: 8,
                r: 5,
                zIndex: 6
            });

        }

        element.add();

        var textX = this.plotLeft + (this.plotWidth * 0.5);
        var textY = this.plotTop + (this.plotHeight * 0.3);

        textX = textX - (element.getBBox().width / 2);

        element.align({ x: textX, y: textY });

        return element;
    }

</script>

<div class="row justify-content-md-center my-2">
    <div class="col-sm-4">
        @{ Html.Action("ProgrammationResourcesStatesPartial", "Integration"); }
    </div>
    <div class="col-sm-4">
        @{ Html.Action("ProgrammationServicesStatesPartial", "Integration"); }
    </div>
</div>
<div class="row my-2">
    <div class="col-sm-4">
        @{ Html.Action("ProgrammationResourcesPerRouteStatesPartial", "Integration"); }
    </div>
    <div class="col-sm-4">
        @{ Html.Action("ProgrammationServicesPerRouteStatesPartial", "Integration"); }
    </div>
    <div class="col-sm-4">
        @{ Html.Action("ProgrammationPerGroupStatesPartial", "Integration"); }
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Prosegur.LV.SOL.Dashboard.UI.Web/Views/Dashboard/ProgrammationBar.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@Scripts.Render("~/bundles/highCharts")

@*<script>

    Highcharts.Chart.prototype.addChartLabel = function (type, message) {

        element = this.renderer.label(message);

        if (type == 'error') {

            element.css({
                color: '#FFFFFF',
                fontSize: '1.1em',
                width: 350
            })
                .attr({
                    fill: '#ff0000',
                    padding: 8,
                    r: 5,
                    zIndex: 6
                });

        }

        if (type == 'warning') {

            element.css({
                color: '#000000',
                fontSize: '3em'
            })
                .attr({
                    fill: '#ffc107',
                    padding: 8,
                    r: 5,
                    zIndex: 6
                });

        }

        element.add();

        var textX = this.plotLeft + (this.plotWidth * 0.5);
        var textY = this.plotTop + (this.plotHeight * 0.3);

        textX = textX - (element.getBBox().width / 2);

        element.align({ x: textX, y: textY });

        return element;
    }



</script>*@

<div class="row my-2">
    <div class="col-sm-4"> <!--- esto es una parcial view que se renderiza con renderaction-->
        @{ Html.RenderAction("ProgrammationBarPerRouteServicesStatesPartial", "Integration"); }
    </div>
    <div class="col-sm-4">
        @{ Html.RenderAction("ProgrammationBarPerRouteResourcesStatesPartial", "Integration"); }
    </div>
    <div class="col-sm-4">
        @{ Html.RenderAction("ProgrammationBarPerGroupStatesPartial", "Integration"); }
    </div>
</div>
<div class="row my-2">
    <div class="col-sm-4">
        @{ Html.RenderPartial("IntegrationBarStateReferencesPartial", Prosegur.LV.SOL.Dashboard.UI.Web.Models.IntegrationBarStateModel.GetAll()); }
    </div>
    <div class="col-sm-4">
        @{ Html.RenderAction("ProgrammationBarServicesStatesPartial", "Integration"); }
    </div>
    <div class="col-sm-4">
        @{ Html.RenderAction("ProgrammationBarResourcesStatesPartial", "Integration"); }
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Prosegur.LV.SOL.Dashboard.UI.Web/Views/Dashboard/Route.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@Scripts.Render("~/bundles/highCharts")

<script>

    Highcharts.Chart.prototype.addChartLabel = function (type, message) {

        element = this.renderer.label(message);

        if (type == 'error') {

            element.css({
                color: '#FFFFFF',
                fontSize: '1.1em',
                width: 350
            })
            .attr({
                fill: '#ff0000',
                padding: 8,
                r: 5,
                zIndex: 6
            });

        }

        if (type == 'warning') {

            element.css({
                color: '#000000',
                fontSize: '3em'
            })
            .attr({
                fill: '#ffc107',
                padding: 8,
                r: 5,
                zIndex: 6
            });

        }

        element.add();

        var textX = this.plotLeft + (this.plotWidth * 0.5);
        var textY = this.plotTop + (this.plotHeight * 0.3);

        textX = textX - (element.getBBox().width / 2);

        element.align({ x: textX, y: textY });

        return element;
    }

</script>

<div class="row justify-content-md-center my-2">
    <div class="col-sm-4">
        @{ Html.RenderAction("RouteBalancesPartial", "Route"); }
    </div>
    <div class="col-sm-4">
        @{ Html.RenderAction("OTIntegrationStatesPartial", "Integration"); }
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}